apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-application
  labels:
    myapp: app
spec:
  replicas: 2
  selector:
    matchLabels:
      myapp: app
  template:
    metadata:
      labels:
        myapp: app
    spec:
      containers:
      - name: flask-web-app
        image: bryanmoh/flask_web-application-web
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    myapp: app
  name: python-web-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 31500
  selector:
    myapp: app
status:
  loadBalancer: {}
